version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  http:
    image: steveltn/https-portal:1
    container_name: http
    volumes:
      - ./ssh_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    links: 
      - web
    environment:
      DOMAINS: "trydjango.passiveradio.com -> http://web:8000/"
      STAGE: "production"
      # FORCE_RENEW: "true"
